// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaWi52bUYGuqbeKwecsHXhhY_c9HkN8To',
    appId: '1:832821075669:web:97ec9c2bb7a8a44d6a8c5c',
    messagingSenderId: '832821075669',
    projectId: 'navi-personal-3e672',
    authDomain: 'navi-personal-3e672.firebaseapp.com',
    databaseURL: 'https://navi-personal-3e672-default-rtdb.firebaseio.com',
    storageBucket: 'navi-personal-3e672.firebasestorage.app',
    measurementId: 'G-N9CNC926WK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASa0JlAiberDfA0RMjGBXgM5DVz70q6v8',
    appId: '1:832821075669:android:9c8fef5802f6a0f16a8c5c',
    messagingSenderId: '832821075669',
    projectId: 'navi-personal-3e672',
    databaseURL: 'https://navi-personal-3e672-default-rtdb.firebaseio.com',
    storageBucket: 'navi-personal-3e672.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8aiHF8xC_U7rDIRueFJMLCC-ho7H3Wws',
    appId: '1:832821075669:ios:1bb0918cb81251fc6a8c5c',
    messagingSenderId: '832821075669',
    projectId: 'navi-personal-3e672',
    databaseURL: 'https://navi-personal-3e672-default-rtdb.firebaseio.com',
    storageBucket: 'navi-personal-3e672.firebasestorage.app',
    iosClientId: '832821075669-2dp2o5t56e2c8dm21p05bs9p4g7irfim.apps.googleusercontent.com',
    iosBundleId: 'com.example.naviPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8aiHF8xC_U7rDIRueFJMLCC-ho7H3Wws',
    appId: '1:832821075669:ios:1bb0918cb81251fc6a8c5c',
    messagingSenderId: '832821075669',
    projectId: 'navi-personal-3e672',
    databaseURL: 'https://navi-personal-3e672-default-rtdb.firebaseio.com',
    storageBucket: 'navi-personal-3e672.firebasestorage.app',
    iosClientId: '832821075669-2dp2o5t56e2c8dm21p05bs9p4g7irfim.apps.googleusercontent.com',
    iosBundleId: 'com.example.naviPersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaWi52bUYGuqbeKwecsHXhhY_c9HkN8To',
    appId: '1:832821075669:web:f4ad9c32cb2db80a6a8c5c',
    messagingSenderId: '832821075669',
    projectId: 'navi-personal-3e672',
    authDomain: 'navi-personal-3e672.firebaseapp.com',
    databaseURL: 'https://navi-personal-3e672-default-rtdb.firebaseio.com',
    storageBucket: 'navi-personal-3e672.firebasestorage.app',
    measurementId: 'G-BS9B69KDGY',
  );
}
