// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDln5iFRSDKz6kWmjzP_22uZgurp68ZELQ',
    appId: '1:712966180400:web:8efc7959836c0cc23ba7f5',
    messagingSenderId: '712966180400',
    projectId: 'project-bc878e6c-6f53-4f24-88a',
    authDomain: 'project-bc878e6c-6f53-4f24-88a.firebaseapp.com',
    storageBucket: 'project-bc878e6c-6f53-4f24-88a.firebasestorage.app',
    measurementId: 'G-30TEKY19JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHSdclU8h_kRCalHtstvw2xgwvkKGkRkg',
    appId: '1:712966180400:android:7de6d6f4a94a33713ba7f5',
    messagingSenderId: '712966180400',
    projectId: 'project-bc878e6c-6f53-4f24-88a',
    storageBucket: 'project-bc878e6c-6f53-4f24-88a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDukqWdjSTBSyAqZl5padytxPVWxgLDNs4',
    appId: '1:712966180400:ios:4ae2e8c4c70a2b683ba7f5',
    messagingSenderId: '712966180400',
    projectId: 'project-bc878e6c-6f53-4f24-88a',
    storageBucket: 'project-bc878e6c-6f53-4f24-88a.firebasestorage.app',
    iosBundleId: 'com.example.naviPersonal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDukqWdjSTBSyAqZl5padytxPVWxgLDNs4',
    appId: '1:712966180400:ios:4ae2e8c4c70a2b683ba7f5',
    messagingSenderId: '712966180400',
    projectId: 'project-bc878e6c-6f53-4f24-88a',
    storageBucket: 'project-bc878e6c-6f53-4f24-88a.firebasestorage.app',
    iosBundleId: 'com.example.naviPersonal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDln5iFRSDKz6kWmjzP_22uZgurp68ZELQ',
    appId: '1:712966180400:web:219361aba509b51e3ba7f5',
    messagingSenderId: '712966180400',
    projectId: 'project-bc878e6c-6f53-4f24-88a',
    authDomain: 'project-bc878e6c-6f53-4f24-88a.firebaseapp.com',
    storageBucket: 'project-bc878e6c-6f53-4f24-88a.firebasestorage.app',
    measurementId: 'G-2BRM2M8SQ4',
  );
}
